name: 'Release'
description: 'Create release'
inputs:
  token:  # github token
    description: 'Github token'
    required: true
outputs:
  releaseId: # release number
    description: 'release id'
  releaseNumber: #version number
    description: 'version number'
runs:
  using: 'node12'
  main: 'dist/index.js'
