name: 'Release'
description: 'Create release'
inputs:
  token:  # github token
    description: 'Github token'
    required: true
  version: 
    description: 'Release version/tag'
    required: true
outputs:
  id: # release number
    description: 'release id'
runs:
  using: 'node16'
  main: 'dist/index.js'
