name: 'Release'
description: 'Create release'
inputs:
  token:  # github token
    description: 'Github token'
    required: true
outputs:
  relaseNumber: # release number
    description: 'release number'
runs:
  using: 'node12'
  main: 'dist/index.js'
